import "server-only";

import { db } from "@/lib/db";
import { opsOccurrenceInclude } from "@/data/ops/includes";
import { buildDateTimeRange } from "@/data/ops/shared";
import { requireAdminSession } from "@/lib/require-admin-session";
import { JobOccurrenceFiltersSchema } from "@/schemas/ops";

// Read-only: visits are generated by hand (generateJobOccurrences), never here.
export const getJobOccurrences = async (filters?: unknown) => {
  try {
    await requireAdminSession();

    const parsedFilters = JobOccurrenceFiltersSchema.safeParse(filters ?? {});
    if (!parsedFilters.success) {
      return { error: "Filtros de ocurrencias invalidos" };
    }

    const {
      jobId,
      employeeId,
      scheduleRuleId,
      statuses,
      includeArchived,
      isDetached,
      startDate,
      endDate,
    } = parsedFilters.data;

    const employeeFilter = employeeId
      ? {
          employees: { some: { employeeId } },
        }
      : {};

    const occurrences = await db.jobOccurrence.findMany({
      where: {
        ...employeeFilter,
        jobId,
        scheduleRuleId,
        NOT: {
          job: {
            archivedAt: {
              not: null,
            },
          },
          status: "SCHEDULED",
        },
        status: statuses?.length ? { in: statuses } : undefined,
        archivedAt: includeArchived ? undefined : null,
        isDetached,
        scheduledStartAt: buildDateTimeRange(startDate, endDate),
      },
      include: opsOccurrenceInclude,
      orderBy: [{ scheduledStartAt: "asc" }],
    });

    return { occurrences };
  } catch (error) {
    console.error("Error getting job occurrences:", error);
    return { error: "Error al obtener las ocurrencias del calendario" };
  }
};
