import "server-only";

import { db } from "@/lib/db";
import {
  findMissingStarts,
  persistOccurrences,
  type RuleForGeneration,
} from "@/lib/ops/job-occurrence-generation-create";
import {
  buildCandidateStarts,
  getRuleGenerationWindow,
  type GenerationRange,
} from "@/lib/ops/job-occurrence-recurrence";
import type { OccurrenceGenerationFilters } from "@/lib/ops/occurrence-generation-range";
import {
  deleteReplaceableOccurrences,
  findReplaceableOccurrences,
} from "@/lib/ops/occurrence-replacement-query";

// Visits are only generated by hand, for a range the user picks (feature 9):
// reads never write. Both commands are idempotent, because a start that
// already has a visit (even archived or moved) is skipped. Visits that no
// longer match their rule are replaced only when the user picks them.

type GenerationPlan = { rule: RuleForGeneration; starts: Date[] };

const getRulesForRange = (
  range: GenerationRange,
  { jobId, scheduleRuleId }: OccurrenceGenerationFilters
): Promise<RuleForGeneration[]> =>
  db.jobScheduleRule.findMany({
    where: {
      id: scheduleRuleId,
      isActive: true,
      jobId,
      job: { archivedAt: null },
      startDate: { lte: range.end },
      OR: [{ endDate: null }, { endDate: { gte: range.start } }],
    },
    include: {
      job: {
        select: {
          assignments: {
            where: {
              archivedAt: null,
              assignedFrom: { lte: range.end },
              OR: [{ assignedTo: null }, { assignedTo: { gte: range.start } }],
            },
            select: { assignedFrom: true, assignedTo: true, employeeId: true },
          },
        },
      },
    },
  });

const planOccurrenceGeneration = async (
  range: GenerationRange,
  filters: OccurrenceGenerationFilters
): Promise<GenerationPlan[]> => {
  const rules = await getRulesForRange(range, filters);
  const plans = await Promise.all(
    rules.map(async (rule) => {
      const window = getRuleGenerationWindow(rule, range);
      const starts = window ? buildCandidateStarts(rule, window) : [];
      return { rule, starts: await findMissingStarts(rule, starts) };
    })
  );

  return plans.filter((plan) => plan.starts.length > 0);
};

const countJobs = (plans: GenerationPlan[]) =>
  new Set(plans.map((plan) => plan.rule.jobId)).size;

// How many visits generating would create, and which ones no longer match
// their rule, without writing anything.
export const previewOccurrenceGeneration = async (
  range: GenerationRange,
  filters: OccurrenceGenerationFilters
) => {
  const [plans, replacement] = await Promise.all([
    planOccurrenceGeneration(range, filters),
    findReplaceableOccurrences(range, filters),
  ]);

  return {
    ...replacement,
    jobs: countJobs(plans),
    visits: plans.reduce((total, plan) => total + plan.starts.length, 0),
  };
};

// Deletes the chosen visits that no longer match (re-checked now), then
// creates every missing one, including the replacements.
export const generateOccurrences = async (
  range: GenerationRange,
  filters: OccurrenceGenerationFilters,
  userId: string,
  replaceIds: string[] = []
) => {
  const deleted = await deleteReplaceableOccurrences(range, filters, replaceIds);
  const plans = await planOccurrenceGeneration(range, filters);
  const counts = await Promise.all(
    plans.map((plan) => persistOccurrences(plan.rule, plan.starts, userId))
  );

  return {
    deleted,
    jobs: countJobs(plans),
    visits: counts.reduce((total, count) => total + count, 0),
  };
};
